# Generated by cucumber-sinatra. (2011-10-13 19:25:33 +0200)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

#Capybara.app = Reingard

class ReingardWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  ReingardWorld.new
end
